name: Cypress Tests — ServeRest

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar smoke teste
        uses: cypress-io/github-action@v6
        with:
          install: false
          command: npx cypress run --env grepTags=@smoke
        env:
          CYPRESS_apiUrl: https://serverest.dev

      - name: Upload de screenshots (em caso de falhas)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: smoke-screenshots
          path: cypress/screenshots/
          retention-days: 7

  critical:
    name: Testes Criticos
    runs-on: ubuntu-latest
    needs: smoke

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar  testes criticos
        uses: cypress-io/github-action@v6
        with:
          install: false
          command: npx cypress run --env grepTags=@critical
        env:
          CYPRESS_apiUrl: https://serverest.dev

      - name: Upload de screenshots (somente caso de falhas)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: critical-screenshots
          path: cypress/screenshots/
          retention-days: 7

  regression:
    name: Testes Regressivos
    runs-on: ubuntu-latest
    needs: [smoke, critical]

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar testes Regressivos
        uses: cypress-io/github-action@v6
        with:
          install: false
          command: npx cypress run --env grepTags=@regression
        env:
          CYPRESS_apiUrl: https://serverest.dev

      - name: Upload do relatório HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/
          retention-days: 15

      - name: Upload de screenshots (somente em falhas)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: regression-screenshots
          path: cypress/screenshots/
          retention-days: 7